name: precursory
version: 0.1.0.0
#synopsis:
#description:
homepage: https://github.com/bryanwtan/precursory#readme
license: BSD3
author: bryan
maintainer: twotale.industries@gmail.com
copyright: MIT-0
category: Web
extra-source-files:
  - README.md

dependencies:
  - base >= 4.7 && < 5

executables:
  precursory:
    source-dirs: src
    main: Main.hs
